#ifndef EXPENSETRACKER_GUI_H
#define EXPENSETRACKER_GUI_H

#include <QWidget>

// Generated by uic from src/GUI.ui at build time; forward-declared here so only
// GUI.cpp needs the generated header
QT_BEGIN_NAMESPACE
namespace Ui { class ExpenseTrackerWindow; }
QT_END_NAMESPACE

// main application window
class GUI : public QWidget {
    Q_OBJECT

public:
    // constructor building the window from the Designer layout
    explicit GUI(QWidget* parent = nullptr);
    // destructor releasing the generated UI
    ~GUI() override;

private:
    Ui::ExpenseTrackerWindow* ui;
};

#endif //EXPENSETRACKER_GUI_H
